### PR TITLE
estat issues

### PR DESCRIPTION
**Pull request by brad-lewis**
commas in the output of keys in estat
estat: too many arguments output when there are too few
estat: remove mandatory final positional duration argument

### CODE REVIEW

**Comment by brad-lewis** [comment]
I fixed a couple of flake8 issues.

**Comment by sebroy** [comment]
Can you reference the GitHub issues you're addressing by formatting your PR and/or commit message as described here? https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by brad-lewis** [comment]
I added a closes line to the commit message.

**Comment by sebroy** [comment]
@brad-lewis can you sync this with master? I'll merge this once that's done.

**Comment by brad-lewis** [comment]
Did a rebase.  Should be ready to go.

**Pull request merged**
