### PR TITLE
Add nfs_threads command

### PR DESCRIPTION
**Pull request by don-brady**
Display NFS thread usage info along with NFS I/O context (for both v3 and v4 clients).

Output Sample:
```
 packets  sockets threads threads metadata  read    read  write   write
 arrived enqueued   woken   used     calls  iops thruput   iops thruput
    4589        0    4589     25        16   273   3.6MB    212   2.6MB
    4735        0    4735      8         1   287   3.8MB    212   2.7MB
    4693        0    4693     10         0   280   3.7MB    216   2.7MB
    4625        0    4625     15         0   278   3.7MB    212   2.6MB
    4687        0    4687      7         1   285   3.8MB    210   2.6MB
    4701        0    4701     12         0   285   3.8MB    215   2.7MB
```

Testing 
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2649/
Confirmed that the added command is present in the built image and runs.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build was run locally and any changes were pushed
- [x] flake8 has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by don-brady** [comment]
Looks like flake8 is applying python2.7 syntax checking to my python3 script.

**Comment by sebroy** [comment]
> Looks like flake8 is applying python2.7 syntax checking to my python3 script.

@don-brady take a look at `.github/workflows/flake8.yml`. In order to get this to work appropriately, we'll need to change that action to have separate jobs for Python 2.7 and Python 3 checking, with the jobs applying to the specific files or directories that are relevant to that Python version.

**Comment by sebroy** [comment]
Either that or we bite the bullet and convert everything over to Python 3 in this repo and change the action to do Python 3 checking across the board. I'd love to see that too.

**Comment by sebroy** [comment]
Or, get https://github.com/delphix/performance-diagnostics/pull/9 merged first, which will remove our dependency on Python 2.7...

**Pull request merged**
